### ISSUE TITLE
feature `cairo-1-hints` compilation error 

### ISSUE THREAD

**Issue by Okm165** [lambdaclass/cairo-vm#1882]
**Describe the bug**
Project fails to compile when features = ["cairo-1-hints"] is added

**To Reproduce**
Build project with following Cargo.toml dependency:
Cargo.toml
```
[package]
name = "tmp"
version = "0.1.0"
edition = "2021"

[dependencies]
cairo-vm = { git = "https://github.com/lambdaclass/cairo-vm", rev = "93f1f54f38059af89850b1c06d4c901300f9b94d", features = ["cairo-1-hints"] }
```

Compile errors message:

```
Compiling cairo-vm v1.0.1 (https://github.com/lambdaclass/cairo-vm?rev=93f1f54f38059af89850b1c06d4c901300f9b94d#93f1f54f)
error[E0275]: overflow evaluating the requirement `for<'r> &'r Simd<_, _>: std::ops::Add`
   --> /home/bartosz/.cargo/git/checkouts/cairo-vm-0c3551b29fd6ce3c/93f1f54/vm/src/math_utils/is_prime.rs:12:9
    |
12  |         num_prime::nt_funcs::is_prime(n, None).probably()
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`cairo_vm`)
    = note: required for `&'r sprs::sparse::CsMatBase<Simd<_, _>, _, _, _, _, _>` to implement `for<'r> std::ops::Add`
    = note: 124 redundant requirements hidden
    = note: required for `&CsVecBase<_, _, CsMatBase<CsMatBase<CsMatBase<..., ..., ..., ..., ..., ...>, ..., ..., ..., ..., ...>, ..., ..., ..., ..., ...>, ...>` to implement `for<'r> std::ops::Add<sprs::sparse::CsVecBase<_, _, sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<Simd<_, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _>>`
    = note: required for `&CsVecBase<_, _, CsMatBase<CsMatBase<CsMatBase<..., ..., ..., ..., ..., ...>, ..., ..., ..., ..., ...>, ..., ..., ..., ..., ...>, ...>` to implement `for<'r> NumOps<sprs::sparse::CsVecBase<_, _, sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<Simd<_, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _>, sprs::sparse::CsVecBase<_, _, sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<Simd<_, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _>>`
    = note: required for `&CsVecBase<_, _, CsMatBase<CsMatBase<CsMatBase<..., ..., ..., ..., ..., ...>, ..., ..., ..., ..., ...>, ..., ..., ..., ..., ...>, ...>` to implement `for<'r> RefNum<sprs::sparse::CsVecBase<_, _, sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<Simd<_, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _>>`
    = note: required for `&CsVecBase<_, _, CsMatBase<CsMatBase<CsMatBase<..., ..., ..., ..., ..., ...>, ..., ..., ..., ..., ...>, ..., ..., ..., ..., ...>, ...>` to implement `for<'r> PrimalityRefBase<sprs::sparse::CsVecBase<_, _, sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<sprs::sparse::CsMatBase<Simd<_, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _, _, _, _, _>, _>>`
note: required by a bound in `num_prime::nt_funcs::is_prime`
   --> /home/bartosz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/num-prime-0.4.4/src/nt_funcs.rs:504:20
    |
502 | pub fn is_prime<T: PrimalityBase>(target: &T, config: Option<PrimalityTestConfig>) -> Primality
    |        -------- required by a bound in this function
503 | where
504 |     for<'r> &'r T: PrimalityRefBase<T>,
    |                    ^^^^^^^^^^^^^^^^^^^ required by this bound in `is_prime`
    = note: the full name for the type has been written to '/home/bartosz/workshop/lambdaclass/tmp/target/debug/deps/cairo_vm-89280f4dbeb56d11.long-type-14996710199877793006.txt'
    = note: consider using `--verbose` to print the full type name to the console
    = note: the full name for the type has been written to '/home/bartosz/workshop/lambdaclass/tmp/target/debug/deps/cairo_vm-89280f4dbeb56d11.long-type-7061164163013100026.txt'
    = note: consider using `--verbose` to print the full type name to the console
    = note: the full name for the type has been written to '/home/bartosz/workshop/lambdaclass/tmp/target/debug/deps/cairo_vm-89280f4dbeb56d11.long-type-7061164163013100026.txt'
    = note: consider using `--verbose` to print the full type name to the console
    = note: the full name for the type has been written to '/home/bartosz/workshop/lambdaclass/tmp/target/debug/deps/cairo_vm-89280f4dbeb56d11.long-type-7061164163013100026.txt'
    = note: consider using `--verbose` to print the full type name to the console

For more information about this error, try `rustc --explain E0275`.
error: could not compile `cairo-vm` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

Version [release v1.0.1](https://github.com/lambdaclass/cairo-vm/commit/93f1f54f38059af89850b1c06d4c901300f9b94d)

**Comment by FrancoGiachetta** [comment]
Hi @Okm165!
That issue was solved in version 2.0.0-rc0. Try switching to that version.

**Comment by FrancoGiachetta** [comment]
@Okm165 I'll close this issue as the solution is to switch to the other version. Please pin us if you need anything else

**Comment by Okm165** [comment]
2.0.0-rc0 didn't solve it form me but
2.0.0-rc1 did
Thanks for help!
